### ISSUE TITLE
Feil i behandlingsaktiviteter - Firefox og Safari

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#3001]
Mange gui-feil i Firefox, se vedlagt fil.
[Behandligsaktiviteter Firefox.pdf](https://github.com/Informasjonsforvaltning/fdk/files/4139022/Behandligsaktiviteter.Firefox.pdf)

### Tasks:
- [x] fix input field layout
- [x] ensure no fields overflow the layout
- [x] add click-away functionality to dropdown fields
- [x] fix spelling mistake somewhere ("BehandlingeN gjelder")
- [x] change field title to "Nødvendige garantier ved overføring til tredjeland eller internasjonale organisasjoner"
- [x] make guarantees field mandatory
- [x] remove word "Eksempel" in help text in "Kilder til personopplysningene"

**Comment by joachim-me** [comment]
[GDPR Firefox 2.pdf](https://github.com/Informasjonsforvaltning/fdk/files/4147153/GDPR.Firefox.2.pdf)
Oppdatert fil.

**Comment by LeneSundsbo** [comment]
![Screenshot 2020-02-03 13 25 12](https://user-images.githubusercontent.com/25385497/73653081-ae2e7c00-4688-11ea-8126-e7a608afe8d2.png)

Gjelder også safari.
