### ISSUE TITLE
[Feature] Tilgang for virksomheten (admin) og administrere sine egne endepunkter i fdk-admin-gui

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#3146]
Som "fdk-admin" i en virksomhet som publiserer en eller flere kataloger i FDK 
ønsker jeg å legge til, endre og fjerne "Data Sources" som skal høstes
slik at jeg har full kontroll over hva min virksomhet publiserer i FDK.

Konsekvensen av å gi virksomheten denne tilgangen er at vi senker terskelen for å test ut høsting i feks demo/staging miljø.

Tre ting må på plass:

- [ ]  Rolle organisasjonsadmin brukes til dette

- [ ]  Tilgangsstyring i fdk-harvest-admin som sørger for at fdk-admin kun ser virksomhetens data sources. 

- [ ] Begrense så bruker bare ser "Data Sources"-fanen

Estimat:
1. Er på plass. Kan gjenbruke rolle som allereie er der.
2. Ca 2 arbeidsdager.

**Comment by lillelars** [comment]
@joebrreg  Alle oppgaver med denne er gjort. Setter klar til akseptanse.

@stigbd  Vi bør skrive en artikkel og publisere for å informere alle virksomheter at dette nå er mulig.

**Comment by stigbd** [comment]
Før vi går hardt ut med dette, bør vi køyre "pilot" med Oslo Kommune. Er dette no tilgjengelig i prod og demo?

**Comment by lillelars** [comment]
@stigbd ja skal være det. Hvem tar dette videre med Oslo Kommune?
